//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by DeviceManageSystem.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDB_WRITESMALL                  110
#define IDB_WRITELARGE                  111
#define IDB_MAIN                        112
#define IDB_BUTTONS                     113
#define IDB_FILELARGE                   114
#define IDB_FILESMALL                   115
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_DeviceManageSysTYPE         130
#define ID_WINDOW_MANAGER               131
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define IDR_PASTE_MENU                  151
#define IDR_WINDOWS_MENU                152
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDR_RIBBON                      307
#define IDD_DIALOG_DEPARTMENT           310
#define IDD_DLGDEVICEDETAIL             311
#define IDB_BITMAP_BEFORE               313
#define IDB_BITMAP_DELETE               314
#define IDB_BITMAP_EXIT                 315
#define IDB_BITMAP_NEW                  316
#define IDB_BITMAP_NEXT                 317
#define IDB_BITMAP_OPEN                 318
#define IDB_BITMAP_PRINT                319
#define IDC_STATIC_KEYWORD              1000
#define IDC_EDIT_KEYWORD                1001
#define IDC_BUTTON_KEYWORD              1002
#define IDC_BUTTON_ADD                  1003
#define IDC_BUTTON_MORE                 1004
#define IDC_BUTTON_COUNT                1005
#define IDC_LIST                        1006
#define IDC_BUTTON_NEW                  1007
#define IDC_BUTTON_DELETE               1008
#define IDC_BUTTON_OPEN                 1009
#define IDC_BUTTON_BEFORE               1010
#define IDC_BUTTON_NEXT                 1011
#define IDC_BUTTON_PRINT                1012
#define IDC_BUTTON_EXIT                 1013
#define IDC_STATIC_NUMBER               1014
#define IDC_EDIT_DEVICE_NAME            1015
#define IDC_EDIT_DEVICE_MODEL           1016
#define IDC_EDI_DEVICE_TYPE             1017
#define IDC_EDIT_DEVICE_ENABLE_DATE     1018
#define IDC_EDIT_DEVICE_CHECK_POINT     1020
#define IDC_EDIT_DEVICE_STANDER_NUMBER  1021
#define IDC_EDIT_DEVICE_APPORVER        1022
#define IDC_EDIT_DEVICE_PARTS           1023
#define IDC_EDIT_DEVICE_AUDITOR         1024
#define IDC_EDIT_DEVICE_EDITOR          1025
#define IDC_EDIT_APPEARANCE_DATE        1026
#define IDC_EDIT_DEVICE_IMPORTANCE      1027
#define IDC_EDIT_DEVICE_STATUE          1028
#define IDC_COMBO_DEVICE_INPORTANCE     1046
#define IDC_COMBO_DEVICE_STATUE         1047
#define IDC_EDIT_DEVICE_CHECK_ITEM      1048
#define IDC_COMBO_DEVICE_TYPE           1049
#define IDC_EDIT_DEVICE_CHECK_TOOL      1050
#define IDC_COMBO_DEVICE_CHECK_ITEM     1053
#define IDC_COMBO_DEVICE_CHECK_TOOL     1054
#define IDC_COMBO_DEVICE_CHECK_CYCLE    1055
#define IDC_BUTTON_SAVE                 1055
#define IDC_COMBO_DEVICE_CHECK_METHOD   1056
#define IDC_COMB_DEVICE_WORKORDER_TYPE  1059
#define IDC_EDIT_DEVICE_DEPARTMENT      1069
#define IDC_EDIT_APPEARANCE_NUM         1070
#define IDC_EDIT_DEVICE_OPERATOR        1071
#define IDC_EDIT_DEVICE_INSTALL_LOCATION 1072
#define IDC_EDIT_DEVICE_DESCRIPTION     1076
#define IDC_EDIT_DEVICE_REMARK          1076
#define IDC_BUTTON16                    1077
#define IDC_BUTTON17                    1078
#define IDC_BUTTON18                    1079
#define IDC_BUTTON19                    1080
#define IDC_BUTTON20                    1081
#define ID_WRITE_PASTEASHYPERLINK       32770
#define ID_BUTTON_NAVIGATION            32771
#define ID_BUTTON_DETAIL                32772
#define ID_BUTTON_MAINTAIN              32773
#define ID_BUTTON_TRANSFER              32774
#define ID_BUTTON_SCRAPPED              32775
#define ID_BUTTONEXIT                   32776
#define ID_BUTTON_EXIT                  32776
#define ID_BUTTON_REPORT                32777
#define ID_BUTTON_PRINT                 32778

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        320
#define _APS_NEXT_COMMAND_VALUE         32779
#define _APS_NEXT_CONTROL_VALUE         1056
#define _APS_NEXT_SYMED_VALUE           312
#endif
#endif
